# Generated by Django 6.0.6 on 2026-07-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_joined_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_tendered',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
