# Generated by Django 5.2.13 on 2026-08-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sale_status_expense_stockadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.shop'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='store.shop'),
        ),
        migrations.AddField(
            model_name='customerdebtledger',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='store.shop'),
        ),
        migrations.AddField(
            model_name='expense',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='store.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.shop'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='store.shop'),
        ),
        migrations.AddField(
            model_name='returnrefund',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.shop'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='store.shop'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='store.shop'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='store.shop'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='store.shop'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='store.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('phone', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('barcode', 'shop')},
        ),
    ]
