# Generated by Django 5.2.13 on 2026-09-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_returnrefund_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='alert_email',
            field=models.EmailField(blank=True, help_text='Email address for low stock alerts', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, help_text='Trigger alert when stock hits this level'),
        ),
    ]
