from django.core.management.base import BaseCommand
from store.models import StoreUser, Category, Product, Customer, Supplier, AuditLog
import decimal

class Command(BaseCommand):
    help = 'Seeds the database with the user\'s custom electronics and hardware store stock.'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding database with custom Lights Electricals and Electronics stock...')

        # Clear existing data
        StoreUser.objects.all().delete()
        Category.objects.all().delete()
        Product.objects.all().delete()
        Customer.objects.all().delete()
        Supplier.objects.all().delete()
        AuditLog.objects.all().delete()

        self.stdout.write('Cleared old logs and stock records.')

        # 1. Create Users
        cashier = StoreUser.objects.create(
            name="Alex Cashier",
            pin="1234",
            role="cashier"
        )
        manager = StoreUser.objects.create(
            name="Willy Manager",
            pin="5555",
            role="manager"
        )
        admin = StoreUser.objects.create(
            name="Super Admin",
            pin="0000",
            role="admin"
        )
        self.stdout.write('Created Store Users (PINs: 1234, 5555, 0000).')

        # 2. Create Suppliers
        sup_eacables = Supplier.objects.create(
            name="East Africa Cables Ltd",
            contact_name="Ken Njoroge",
            phone="+254 711 000111",
            email="sales@eacables.com",
            address="Commercial Street, Industrial Area, Nairobi",
            outstanding_balance=decimal.Decimal("120000.00")
        )
        sup_amaya = Supplier.objects.create(
            name="Amaya Distributors East Africa",
            contact_name="Priscilla Musembi",
            phone="+254 722 000222",
            email="support@amayadistributors.com",
            address="Mombasa Road, Nairobi",
            outstanding_balance=decimal.Decimal("85000.00")
        )
        sup_general = Supplier.objects.create(
            name="Nairobi Hardware & Electronics Wholesalers",
            contact_name="David Kiptoo",
            phone="+254 733 000333",
            email="info@nairobihw.co.ke",
            address="Nyamakima, Nairobi",
            outstanding_balance=decimal.Decimal("150000.00")
        )
        self.stdout.write('Created Suppliers.')

        # 3. Create Customers
        Customer.objects.create(
            name="Walk-In Customer",
            phone="0000000000",
            email="",
            loyalty_points=0
        )
        Customer.objects.create(
            name="James Mwangi",
            phone="+254712345678",
            email="james.mwangi@gmail.com",
            loyalty_points=150
        )
        Customer.objects.create(
            name="Sarah Amina",
            phone="+254722334455",
            email="sarah.amina@yahoo.com",
            loyalty_points=85
        )
        self.stdout.write('Created Customer Accounts.')

        # Define custom categories
        categories_data = {
            "Cables & Connectors": "USB smart cables, Type-C cables, jacks, couplers, HDMI, and VGA adaptors.",
            "Earphones & Audio": "Wired earphones, wireless Bluetooth headsets, amplifiers, and tweeter pairs.",
            "Chargers & Adapters": "Wall plugs, smart adapters, car chargers, and multi-power chargers.",
            "Batteries & Power Systems": "Phone batteries, drycell batteries (2A/3A), solar controllers, solar panels, and inverters.",
            "Storage Media": "Memory cards (MicroSD) and flash drives from 2GB to 64GB.",
            "Hardware & Hand Tools": "Hinges, saws, nails, spanners, pliers, screwdrivers, tape measures, and padlocks.",
            "Lighting & Torches": "Rechargeable flashlights, led bulbs, floodlights, tube glasses, fixtures, and Xmas lights.",
            "Electrical Fittings & Switches": "Extensions, bulb holders, single/double switches, single/double sockets, conduits, and trunking.",
            "Electronics & Small Appliances": "Kinyozi clippers, decoders, signal finders, iron boxes, water heaters, and TVs."
        }

        categories = {}
        for cat_name, cat_desc in categories_data.items():
            categories[cat_name] = Category.objects.create(name=cat_name, description=cat_desc)

        self.stdout.write('Created custom Product Categories.')

        # Helper to batch create products
        products_to_create = [
            # 1. Cables & Connectors
            {"barcode": "CAB-OR-SAT", "name": "Oraimo Satchet Cable", "cat": "Cables & Connectors", "cost": 150, "retail": 250, "stock": 50, "serial": False},
            {"barcode": "CAB-OR-BOX", "name": "Oraimo Box Cable", "cat": "Cables & Connectors", "cost": 220, "retail": 400, "stock": 40, "serial": False},
            {"barcode": "CAB-SAM-C70", "name": "Samsung C70 Cable", "cat": "Cables & Connectors", "cost": 180, "retail": 300, "stock": 35, "serial": False},
            {"barcode": "CAB-OPP-C70", "name": "Oppo C70 Cable", "cat": "Cables & Connectors", "cost": 180, "retail": 300, "stock": 30, "serial": False},
            {"barcode": "CAB-TEC-C70", "name": "Tecno C70 Cable", "cat": "Cables & Connectors", "cost": 180, "retail": 300, "stock": 30, "serial": False},
            {"barcode": "CAB-AM-101", "name": "Amaya AM-101 Cable", "cat": "Cables & Connectors", "cost": 120, "retail": 200, "stock": 60, "serial": False},
            {"barcode": "CAB-PU-300", "name": "Pumex PU-300 Cable", "cat": "Cables & Connectors", "cost": 140, "retail": 250, "stock": 45, "serial": False},
            {"barcode": "CAB-PU-100", "name": "Pumex PU-100 Smart Cable", "cat": "Cables & Connectors", "cost": 100, "retail": 180, "stock": 50, "serial": False},
            {"barcode": "CAB-AM-ET10", "name": "Amaya ET-10 Cable", "cat": "Cables & Connectors", "cost": 130, "retail": 220, "stock": 40, "serial": False},
            {"barcode": "CAB-2F-TEC", "name": "2 Fast Tecno Cable", "cat": "Cables & Connectors", "cost": 100, "retail": 180, "stock": 50, "serial": False},
            {"barcode": "CAB-2F-ITEL", "name": "2 Fast Itel Cable", "cat": "Cables & Connectors", "cost": 100, "retail": 180, "stock": 50, "serial": False},
            {"barcode": "CAB-AM-3A", "name": "Amaya 3A Charging Cable", "cat": "Cables & Connectors", "cost": 150, "retail": 250, "stock": 45, "serial": False},
            {"barcode": "CAB-2F-AMZ", "name": "2 Fast Amazon Cable", "cat": "Cables & Connectors", "cost": 120, "retail": 200, "stock": 30, "serial": False},
            {"barcode": "CAB-2F-SAM", "name": "2 Fast Samsung Cable", "cat": "Cables & Connectors", "cost": 100, "retail": 180, "stock": 40, "serial": False},
            {"barcode": "CAB-UI-SMART", "name": "U&I Smart Cable", "cat": "Cables & Connectors", "cost": 150, "retail": 250, "stock": 40, "serial": False},
            {"barcode": "CAB-AD-1600", "name": "Aideepo AD-1600 Cable", "cat": "Cables & Connectors", "cost": 130, "retail": 220, "stock": 35, "serial": False},
            {"barcode": "CAB-AD-1380", "name": "Aideepo AD-1380 Cable", "cat": "Cables & Connectors", "cost": 130, "retail": 220, "stock": 35, "serial": False},
            {"barcode": "CAB-XS-161", "name": "X-Scoot CL-161 Cable", "cat": "Cables & Connectors", "cost": 110, "retail": 200, "stock": 50, "serial": False},
            {"barcode": "CHG-K02TC", "name": "DC Charger K-02TC Cable", "cat": "Cables & Connectors", "cost": 140, "retail": 250, "stock": 30, "serial": False},
            {"barcode": "CAB-TC-C90", "name": "Power C90 Type-C Cable", "cat": "Cables & Connectors", "cost": 180, "retail": 300, "stock": 40, "serial": False},
            {"barcode": "CAB-TC-PU100", "name": "Pumex PU-100 Type-C Cable", "cat": "Cables & Connectors", "cost": 130, "retail": 220, "stock": 40, "serial": False},
            {"barcode": "CAB-TC-SUPER", "name": "Super Energy Type-C Cable", "cat": "Cables & Connectors", "cost": 150, "retail": 250, "stock": 45, "serial": False},
            {"barcode": "CAB-TC-AMC6A", "name": "Amaya AM-C6A Type-C Cable", "cat": "Cables & Connectors", "cost": 160, "retail": 280, "stock": 35, "serial": False},
            {"barcode": "CAB-TC-ORABOX", "name": "Oraimo Box Type-C Cable", "cat": "Cables & Connectors", "cost": 220, "retail": 380, "stock": 30, "serial": False},
            {"barcode": "CAB-TC-ACD77", "name": "Amaya ACD77 Type-C Cable", "cat": "Cables & Connectors", "cost": 160, "retail": 280, "stock": 35, "serial": False},
            {"barcode": "CAB-TC-PU310", "name": "Pumex PU-310 Type-C Cable", "cat": "Cables & Connectors", "cost": 140, "retail": 250, "stock": 30, "serial": False},
            {"barcode": "CAB-TC-AD1610", "name": "Aideepo AD-1610 Type-C Cable", "cat": "Cables & Connectors", "cost": 150, "retail": 250, "stock": 40, "serial": False},
            {"barcode": "CAB-TC-AD1720", "name": "Aideepo Satchet AD-1720 Cable", "cat": "Cables & Connectors", "cost": 120, "retail": 200, "stock": 50, "serial": False},
            {"barcode": "CAB-TC-ORASAT", "name": "Oraimo Satchet Type-C Cable", "cat": "Cables & Connectors", "cost": 150, "retail": 250, "stock": 50, "serial": False},
            {"barcode": "CAB-TC-AD118", "name": "Aideepo AD-118 Type-C Cable", "cat": "Cables & Connectors", "cost": 110, "retail": 200, "stock": 40, "serial": False},
            {"barcode": "CAB-SAM-CC", "name": "Samsung C to C Cable", "cat": "Cables & Connectors", "cost": 280, "retail": 500, "stock": 30, "serial": False},
            {"barcode": "CAB-ADPRO6-CC", "name": "Aideepo Pro 6 60W C to C", "cat": "Cables & Connectors", "cost": 320, "retail": 600, "stock": 25, "serial": False},
            {"barcode": "CAB-AD-1390-IP", "name": "Aideepo AD-1390 iPhone Cable", "cat": "Cables & Connectors", "cost": 160, "retail": 280, "stock": 35, "serial": False},
            {"barcode": "CAB-PU-100-IP", "name": "Pumex PU-100 iPhone Cable", "cat": "Cables & Connectors", "cost": 150, "retail": 250, "stock": 30, "serial": False},
            {"barcode": "CAB-PU-CIPH", "name": "Pumex C to iPhone Cable", "cat": "Cables & Connectors", "cost": 250, "retail": 450, "stock": 20, "serial": False},
            {"barcode": "CAB-USB-USB", "name": "USB to USB Connection Cable", "cat": "Cables & Connectors", "cost": 150, "retail": 280, "stock": 25, "serial": False},
            {"barcode": "CAB-HDMI", "name": "HDMI High-Speed Cable 1.5m", "cat": "Cables & Connectors", "cost": 200, "retail": 350, "stock": 40, "serial": False},
            {"barcode": "CAB-VGA", "name": "VGA Laptop to TV Cable", "cat": "Cables & Connectors", "cost": 250, "retail": 450, "stock": 15, "serial": False},
            {"barcode": "CAB-RLINK", "name": "R Link Cable Connector", "cat": "Cables & Connectors", "cost": 180, "retail": 300, "stock": 20, "serial": False},
            {"barcode": "JACK-NORM-33", "name": "Normal Jack 3 by 3 Cable", "cat": "Cables & Connectors", "cost": 150, "retail": 250, "stock": 30, "serial": False},
            {"barcode": "JACK-NORM-21", "name": "Normal Jack 2 by 1 Cable", "cat": "Cables & Connectors", "cost": 120, "retail": 200, "stock": 35, "serial": False},
            {"barcode": "JACK-NORM-11", "name": "Normal Jack 1 by 1 Cable", "cat": "Cables & Connectors", "cost": 100, "retail": 180, "stock": 40, "serial": False},
            {"barcode": "JACK-HEVY-33", "name": "Heavy Jack 3 by 3 Cable", "cat": "Cables & Connectors", "cost": 220, "retail": 380, "stock": 25, "serial": False},
            {"barcode": "JACK-HEVY-21", "name": "Heavy Jack 2 by 1 Cable", "cat": "Cables & Connectors", "cost": 180, "retail": 300, "stock": 25, "serial": False},
            {"barcode": "JACK-HEVY-11", "name": "Heavy Jack 1 by 1 Cable", "cat": "Cables & Connectors", "cost": 150, "retail": 250, "stock": 30, "serial": False},
            {"barcode": "CAB-RAD-2P", "name": "Radio 2-Pin Cable", "cat": "Cables & Connectors", "cost": 80, "retail": 150, "stock": 50, "serial": False},
            {"barcode": "CAB-RAD-3P", "name": "Radio 3-Pin Cable", "cat": "Cables & Connectors", "cost": 100, "retail": 180, "stock": 40, "serial": False},
            {"barcode": "OTG-SMART", "name": "OTG Kit Smart Connector", "cat": "Cables & Connectors", "cost": 60, "retail": 120, "stock": 60, "serial": False},
            {"barcode": "OTG-TYPEC", "name": "OTG Kit Type-C Connector", "cat": "Cables & Connectors", "cost": 80, "retail": 150, "stock": 65, "serial": False},

            # 2. Earphones & Audio
            {"barcode": "EAR-ABD17", "name": "AB D-17 Earphones", "cat": "Earphones & Audio", "cost": 120, "retail": 220, "stock": 40, "serial": False},
            {"barcode": "EAR-SAMST10", "name": "Samsung ST-10 Earphones", "cat": "Earphones & Audio", "cost": 130, "retail": 250, "stock": 35, "serial": False},
            {"barcode": "EAR-SAMBT", "name": "Samsung BT Bluetooth Earpieces", "cat": "Earphones & Audio", "cost": 450, "retail": 800, "stock": 15, "serial": False},
            {"barcode": "EAR-OFIAHTS10", "name": "Ofia HT-S10 Earphones", "cat": "Earphones & Audio", "cost": 140, "retail": 250, "stock": 30, "serial": False},
            {"barcode": "EAR-OFIAHT21", "name": "Ofia HT-21 Earphones", "cat": "Earphones & Audio", "cost": 150, "retail": 280, "stock": 25, "serial": False},
            {"barcode": "EAR-OPPST10", "name": "Oppo ST-10 Earphones", "cat": "Earphones & Audio", "cost": 120, "retail": 220, "stock": 30, "serial": False},
            {"barcode": "EAR-JBL", "name": "JBL Wired Bass Earphones", "cat": "Earphones & Audio", "cost": 150, "retail": 300, "stock": 45, "serial": False},
            {"barcode": "EAR-VIVST10", "name": "Vivo ST-10 Earphones", "cat": "Earphones & Audio", "cost": 120, "retail": 220, "stock": 35, "serial": False},
            {"barcode": "EAR-RXD", "name": "RXD Audio Earphones", "cat": "Earphones & Audio", "cost": 100, "retail": 180, "stock": 40, "serial": False},
            {"barcode": "EAR-AM11", "name": "Amaya 11 Earphones", "cat": "Earphones & Audio", "cost": 110, "retail": 200, "stock": 50, "serial": False},
            {"barcode": "EAR-DRLEE", "name": "Dr Lee Acoustic Earphones", "cat": "Earphones & Audio", "cost": 130, "retail": 240, "stock": 30, "serial": False},
            {"barcode": "EAR-SCOP365", "name": "Scopper 365 Earphones", "cat": "Earphones & Audio", "cost": 120, "retail": 220, "stock": 40, "serial": False},
            {"barcode": "EAR-ORASAT", "name": "Oraimo Satchet Earphones", "cat": "Earphones & Audio", "cost": 150, "retail": 250, "stock": 50, "serial": False},
            {"barcode": "EAR-UI8847", "name": "U&I 8847 Neckband Headset", "cat": "Earphones & Audio", "cost": 380, "retail": 700, "stock": 20, "serial": False},
            {"barcode": "EAR-FPMS10", "name": "FPM S10 Earphones", "cat": "Earphones & Audio", "cost": 140, "retail": 250, "stock": 25, "serial": False},
            {"barcode": "EAR-HIFIEP01", "name": "HIFI Sound EP-01 Earphones", "cat": "Earphones & Audio", "cost": 160, "retail": 300, "stock": 30, "serial": False},
            {"barcode": "EAR-A88", "name": "A88 Stereo Earphones", "cat": "Earphones & Audio", "cost": 110, "retail": 200, "stock": 35, "serial": False},
            {"barcode": "POD-JBL", "name": "JBL Wireless Earpods", "cat": "Earphones & Audio", "cost": 900, "retail": 1500, "stock": 10, "serial": False},
            {"barcode": "EAR-SE-ER100", "name": "Super Energy Naked ER-100", "cat": "Earphones & Audio", "cost": 180, "retail": 300, "stock": 30, "serial": False},
            {"barcode": "EAR-UI-NECK", "name": "U&I Naked Band Bluetooth", "cat": "Earphones & Audio", "cost": 500, "retail": 950, "stock": 15, "serial": False},
            {"barcode": "POD-SE-ER300", "name": "Super Energy ER-300 Pods", "cat": "Earphones & Audio", "cost": 850, "retail": 1450, "stock": 12, "serial": False},
            {"barcode": "EAR-OFIAHT006", "name": "Ofia HT-006 Earphones", "cat": "Earphones & Audio", "cost": 150, "retail": 280, "stock": 25, "serial": False},
            {"barcode": "POD-AD", "name": "Aideepo Earpods Wireless", "cat": "Earphones & Audio", "cost": 750, "retail": 1300, "stock": 15, "serial": False},
            {"barcode": "EAR-ADJ610", "name": "Aideepo AD-J610 Earphones", "cat": "Earphones & Audio", "cost": 130, "retail": 240, "stock": 30, "serial": False},
            {"barcode": "EAR-AMAEP13", "name": "Amaya AEP-13 Earphones", "cat": "Earphones & Audio", "cost": 120, "retail": 220, "stock": 40, "serial": False},
            {"barcode": "TWT-OVAL-1006", "name": "Tweeter Ovaldio TP-1006 (Pair)", "cat": "Earphones & Audio", "cost": 450, "retail": 800, "stock": 15, "serial": False},
            {"barcode": "TWT-006A", "name": "Tweeter 006A (Pair)", "cat": "Earphones & Audio", "cost": 350, "retail": 650, "stock": 20, "serial": False},
            {"barcode": "TWT-005A", "name": "Tweeter 005A (Pair)", "cat": "Earphones & Audio", "cost": 350, "retail": 650, "stock": 20, "serial": False},
            {"barcode": "TWT-004A", "name": "Tweeter 004A (Pair)", "cat": "Earphones & Audio", "cost": 350, "retail": 650, "stock": 20, "serial": False},
            {"barcode": "TWT-TX350-SNG", "name": "Tweeter TX-350 Single", "cat": "Earphones & Audio", "cost": 200, "retail": 380, "stock": 15, "serial": False},
            {"barcode": "TWT-PIONEER", "name": "Tweeter Pioneer Heavy-Duty", "cat": "Earphones & Audio", "cost": 600, "retail": 1100, "stock": 10, "serial": False},
            {"barcode": "TWT-YELLOW", "name": "Tweeter Yellow Series (Pair)", "cat": "Earphones & Audio", "cost": 300, "retail": 550, "stock": 18, "serial": False},
            {"barcode": "TWT-PLASTIC", "name": "Tweeter Plastic Bracket (Pair)", "cat": "Earphones & Audio", "cost": 250, "retail": 450, "stock": 25, "serial": False},
            {"barcode": "AMP-HIFI-698", "name": "Amplifier Hifi Stereo 698", "cat": "Earphones & Audio", "cost": 1800, "retail": 2800, "stock": 4, "serial": True, "serials": "AMP698-001,AMP698-002,AMP698-003,AMP698-004"},
            {"barcode": "AMP-KINT-120", "name": "Amplifier MA-120 Kinter", "cat": "Earphones & Audio", "cost": 1500, "retail": 2400, "stock": 3, "serial": True, "serials": "KINT120-001,KINT120-002,KINT120-003"},
            {"barcode": "AMP-MOONTEK", "name": "Amplifier Moontek Pro", "cat": "Earphones & Audio", "cost": 2200, "retail": 3500, "stock": 2, "serial": True, "serials": "MNKPRO-1091,MNKPRO-1092"},

            # 3. Chargers & Adapters
            {"barcode": "CHG-AM-AD036", "name": "Amaya AD-036 Smart Charger", "cat": "Chargers & Adapters", "cost": 250, "retail": 450, "stock": 30, "serial": False},
            {"barcode": "CHG-AM-FAD109", "name": "Amaya F-AD-109 Fast Charger", "cat": "Chargers & Adapters", "cost": 320, "retail": 600, "stock": 25, "serial": False},
            {"barcode": "CHG-SE-01", "name": "Super Energy SE-01 Charger", "cat": "Chargers & Adapters", "cost": 200, "retail": 380, "stock": 40, "serial": False},
            {"barcode": "CHG-SE-03", "name": "Super Energy SE-03 Charger", "cat": "Chargers & Adapters", "cost": 220, "retail": 400, "stock": 30, "serial": False},
            {"barcode": "CHG-S3X", "name": "Super 3X Smart Charger plug", "cat": "Chargers & Adapters", "cost": 180, "retail": 350, "stock": 35, "serial": False},
            {"barcode": "CHG-SE-08", "name": "Super Energy SE-08 Charger", "cat": "Chargers & Adapters", "cost": 250, "retail": 450, "stock": 30, "serial": False},
            {"barcode": "CHG-HYC207", "name": "HYC-207 Smart Charger", "cat": "Chargers & Adapters", "cost": 160, "retail": 300, "stock": 45, "serial": False},
            {"barcode": "CHG-HYC206", "name": "HYC-206 Smart Charger", "cat": "Chargers & Adapters", "cost": 160, "retail": 300, "stock": 45, "serial": False},
            {"barcode": "CHG-AM-AD034", "name": "Amaya AD-034 Smart Charger", "cat": "Chargers & Adapters", "cost": 240, "retail": 450, "stock": 35, "serial": False},
            {"barcode": "CHG-FAKITOT", "name": "FA-KiTOT Smart Fast Charger", "cat": "Chargers & Adapters", "cost": 280, "retail": 500, "stock": 20, "serial": False},
            {"barcode": "CHG-TRV-4G", "name": "Travel 4G Power Charger", "cat": "Chargers & Adapters", "cost": 190, "retail": 350, "stock": 40, "serial": False},
            {"barcode": "CHG-EXC-SMR", "name": "Excellent Smart Charger Adapter", "cat": "Chargers & Adapters", "cost": 150, "retail": 280, "stock": 50, "serial": False},
            {"barcode": "CHG-AM-YY180", "name": "Amaya YY-180 Smart Charger", "cat": "Chargers & Adapters", "cost": 280, "retail": 500, "stock": 25, "serial": False},
            {"barcode": "CHG-IT-MICRO", "name": "Itel Micro USB Wall Charger", "cat": "Chargers & Adapters", "cost": 150, "retail": 280, "stock": 50, "serial": False},
            {"barcode": "CHG-HOYAN-DT", "name": "Hoyan DT Mobile Charger", "cat": "Chargers & Adapters", "cost": 180, "retail": 300, "stock": 30, "serial": False},
            {"barcode": "CHG-MP-C8028", "name": "Multiple Power MY-C8028MP Charger", "cat": "Chargers & Adapters", "cost": 300, "retail": 550, "stock": 20, "serial": False},
            {"barcode": "CHG-PU-JY02M", "name": "Pumex JY-02 Metal Stand Charger", "cat": "Chargers & Adapters", "cost": 350, "retail": 650, "stock": 15, "serial": False},
            {"barcode": "CHG-PU-JY503", "name": "Pumex JY-503 Type-C Charger", "cat": "Chargers & Adapters", "cost": 280, "retail": 500, "stock": 25, "serial": False},
            {"barcode": "CHG-EXC-TC", "name": "Excellent Type-C Fast Charger", "cat": "Chargers & Adapters", "cost": 200, "retail": 380, "stock": 30, "serial": False},
            {"barcode": "CHG-AM-AD028", "name": "Amaya AD-028 Type-C Charger", "cat": "Chargers & Adapters", "cost": 260, "retail": 480, "stock": 25, "serial": False},
            {"barcode": "CHG-PU-JY501", "name": "Pumex JY-501 Type-C Charger", "cat": "Chargers & Adapters", "cost": 280, "retail": 500, "stock": 20, "serial": False},
            {"barcode": "CHG-AD-C315", "name": "Aideepo AD-C315 Type-C Charger", "cat": "Chargers & Adapters", "cost": 240, "retail": 450, "stock": 35, "serial": False},
            {"barcode": "CHG-OR-IPH", "name": "Oraimo iPhone Fast Charger", "cat": "Chargers & Adapters", "cost": 450, "retail": 800, "stock": 20, "serial": False},
            {"barcode": "CHG-PU-JY740", "name": "Pumex JY-740 C to C Charger", "cat": "Chargers & Adapters", "cost": 400, "retail": 750, "stock": 15, "serial": False},
            {"barcode": "CHG-SAM-25W", "name": "Samsung 25W C to C Charger plug", "cat": "Chargers & Adapters", "cost": 850, "retail": 1500, "stock": 15, "serial": False},
            {"barcode": "CHG-SAM-45W", "name": "Samsung 45W C to C Super Charger", "cat": "Chargers & Adapters", "cost": 1400, "retail": 2400, "stock": 10, "serial": False},
            {"barcode": "ADP-AM-GAD12", "name": "Amaya GAD-012 OTG Adapter", "cat": "Chargers & Adapters", "cost": 150, "retail": 300, "stock": 40, "serial": False},
            {"barcode": "ADP-AM-GAD13", "name": "Amaya GAD-013 OTG Adapter", "cat": "Chargers & Adapters", "cost": 150, "retail": 300, "stock": 40, "serial": False},
            {"barcode": "ADP-TECNO", "name": "Tecno Charger Adapter Plug", "cat": "Chargers & Adapters", "cost": 120, "retail": 200, "stock": 50, "serial": False},
            {"barcode": "ADP-SE-05", "name": "Super Energy SE-05 Adapter", "cat": "Chargers & Adapters", "cost": 180, "retail": 320, "stock": 30, "serial": False},
            {"barcode": "ADP-3PIN-WHT", "name": "3-Pin White Converter Adapter", "cat": "Chargers & Adapters", "cost": 100, "retail": 200, "stock": 60, "serial": False},
            {"barcode": "ADP-DECODER", "name": "Decoder Power Supply Adapter", "cat": "Chargers & Adapters", "cost": 150, "retail": 300, "stock": 40, "serial": False},
            {"barcode": "ADP-AM-AD014", "name": "Amaya AD-014 Power Adapter", "cat": "Chargers & Adapters", "cost": 220, "retail": 400, "stock": 30, "serial": False},
            {"barcode": "ADP-PWR-BOOST", "name": "Power Booster Voltage Adapter", "cat": "Chargers & Adapters", "cost": 300, "retail": 550, "stock": 20, "serial": False},
            {"barcode": "ADP-KAIAODI", "name": "Kaiaodi Power Supply Adaptor", "cat": "Chargers & Adapters", "cost": 250, "retail": 450, "stock": 25, "serial": False},
            {"barcode": "ADP-AD-C128", "name": "Aideepo AD-C128 Universal Adapter", "cat": "Chargers & Adapters", "cost": 350, "retail": 650, "stock": 15, "serial": False},
            {"barcode": "CAR-CHG-IT15", "name": "Car Charger Itel 15.5W", "cat": "Chargers & Adapters", "cost": 250, "retail": 450, "stock": 20, "serial": False},
            {"barcode": "CAR-PLAY-X8", "name": "Car Player X8 Bluetooth FM", "cat": "Chargers & Adapters", "cost": 450, "retail": 800, "stock": 15, "serial": False},
            {"barcode": "CAR-CHG-G7", "name": "Car G7 FM Transmitter Charger", "cat": "Chargers & Adapters", "cost": 380, "retail": 700, "stock": 25, "serial": False},
            {"barcode": "CAR-FM-TRANS", "name": "FM Transmitter Bluetooth Car Kit", "cat": "Chargers & Adapters", "cost": 450, "retail": 800, "stock": 20, "serial": False},
            {"barcode": "CAR-CHG-PREM", "name": "Premium Car Charger Dual USB", "cat": "Chargers & Adapters", "cost": 350, "retail": 600, "stock": 20, "serial": False},
            {"barcode": "CAR-CHG-A903", "name": "Original A903 Car Charger", "cat": "Chargers & Adapters", "cost": 280, "retail": 500, "stock": 30, "serial": False},
            {"barcode": "CAR-CHG-K910", "name": "KCB-910 High Current Car Charger", "cat": "Chargers & Adapters", "cost": 300, "retail": 550, "stock": 25, "serial": False},
            {"barcode": "CAR-AM-ACC08", "name": "Amaya ACC-CC08X Type-C Car", "cat": "Chargers & Adapters", "cost": 400, "retail": 750, "stock": 15, "serial": False},
            {"barcode": "CAR-AD-AD13", "name": "Aideepo AD-13 Type-C Car Charger", "cat": "Chargers & Adapters", "cost": 380, "retail": 700, "stock": 20, "serial": False},
            {"barcode": "CAR-XS-XC303", "name": "X-Scoot XC-303 Type-C Car", "cat": "Chargers & Adapters", "cost": 350, "retail": 650, "stock": 20, "serial": False},
            {"barcode": "CAR-SAM-TC", "name": "Samsung Type-C Fast Car Charger", "cat": "Chargers & Adapters", "cost": 500, "retail": 900, "stock": 15, "serial": False},

            # 4. Batteries & Power Systems
            {"barcode": "BAT-ITEL-5CO", "name": "Itel 5C Original Phone Battery", "cat": "Batteries & Power Systems", "cost": 350, "retail": 650, "stock": 15, "serial": False},
            {"barcode": "BAT-TEC-5CC", "name": "Tecno 5C Copy Phone Battery", "cat": "Batteries & Power Systems", "cost": 150, "retail": 300, "stock": 30, "serial": False},
            {"barcode": "BAT-TRIP-5C", "name": "Triple 5C Phone Battery Pack", "cat": "Batteries & Power Systems", "cost": 180, "retail": 350, "stock": 25, "serial": False},
            {"barcode": "BAT-VILL-5C", "name": "Villaontel 5C Phone Battery", "cat": "Batteries & Power Systems", "cost": 220, "retail": 400, "stock": 20, "serial": False},
            {"barcode": "BAT-ITEL-5CC", "name": "Itel 5C Copy Phone Battery", "cat": "Batteries & Power Systems", "cost": 150, "retail": 300, "stock": 30, "serial": False},
            {"barcode": "BAT-AD-LION", "name": "Aideepo Lion Lithium Battery", "cat": "Batteries & Power Systems", "cost": 250, "retail": 450, "stock": 20, "serial": False},
            {"barcode": "DRY-TOY-2A", "name": "Drycell Toyoeba AA Battery", "cat": "Batteries & Power Systems", "cost": 15, "retail": 30, "stock": 200, "serial": False},
            {"barcode": "DRY-TOY-3A", "name": "Drycell Toyoeba AAA Battery", "cat": "Batteries & Power Systems", "cost": 15, "retail": 30, "stock": 200, "serial": False},
            {"barcode": "DRY-EVE-2A", "name": "Drycell Eveready AA Battery", "cat": "Batteries & Power Systems", "cost": 25, "retail": 50, "stock": 150, "serial": False},
            {"barcode": "DRY-EVE-3A", "name": "Drycell Eveready AAA Battery", "cat": "Batteries & Power Systems", "cost": 25, "retail": 50, "stock": 150, "serial": False},
            {"barcode": "DRY-AM-2A", "name": "Drycell Amaya AA Heavy Duty", "cat": "Batteries & Power Systems", "cost": 20, "retail": 40, "stock": 100, "serial": False},
            {"barcode": "DRY-GETTOP", "name": "Drycell Mic Gettop Battery", "cat": "Batteries & Power Systems", "cost": 15, "retail": 30, "stock": 120, "serial": False},
            {"barcode": "DRY-GLION", "name": "Drycell Golden Lion Battery", "cat": "Batteries & Power Systems", "cost": 15, "retail": 30, "stock": 120, "serial": False},
            {"barcode": "SOL-PAN-20W", "name": "Solar Panel 20W Photo-Voltaic", "cat": "Batteries & Power Systems", "cost": 1800, "retail": 2800, "stock": 5, "serial": False},
            {"barcode": "SOL-PAN-50W", "name": "Solar Panel 50W Photo-Voltaic", "cat": "Batteries & Power Systems", "cost": 3200, "retail": 4800, "stock": 4, "serial": False},
            {"barcode": "SOL-PAN-80W", "name": "Solar Panel 80W Photo-Voltaic", "cat": "Batteries & Power Systems", "cost": 4800, "retail": 7200, "stock": 3, "serial": False},
            {"barcode": "SOL-PAN-100W", "name": "Solar Panel 100W Photo-Voltaic", "cat": "Batteries & Power Systems", "cost": 5800, "retail": 8500, "stock": 3, "serial": False},
            {"barcode": "SOL-CTRL-20A", "name": "Solar Charge Controller 20A", "cat": "Batteries & Power Systems", "cost": 1200, "retail": 2200, "stock": 4, "serial": True, "serials": "CTR20A-001,CTR20A-002,CTR20A-003,CTR20A-004"},
            {"barcode": "SOL-CTRL-30A", "name": "Solar Charge Controller 30A", "cat": "Batteries & Power Systems", "cost": 1800, "retail": 3000, "stock": 3, "serial": True, "serials": "CTR30A-901,CTR30A-902,CTR30A-903"},
            {"barcode": "SOL-INV-300W", "name": "Solar Power Inverter 300W", "cat": "Batteries & Power Systems", "cost": 2800, "retail": 4500, "stock": 2, "serial": True, "serials": "INV300W-551,INV300W-552"},
            {"barcode": "CHG-BAT-20W", "name": "Rechargeable Battery 20W (3720)", "cat": "Batteries & Power Systems", "cost": 300, "retail": 550, "stock": 20, "serial": False},
            {"barcode": "CHG-BAT-30W", "name": "Rechargeable Battery 30W (3730)", "cat": "Batteries & Power Systems", "cost": 380, "retail": 700, "stock": 18, "serial": False},
            {"barcode": "CHG-BAT-40W", "name": "Rechargeable Battery 40W (3740)", "cat": "Batteries & Power Systems", "cost": 450, "retail": 850, "stock": 15, "serial": False},
            {"barcode": "CHG-BAT-50W", "name": "Rechargeable Battery 50W (3750)", "cat": "Batteries & Power Systems", "cost": 550, "retail": 1000, "stock": 15, "serial": False},
            {"barcode": "CHG-BAT-100W", "name": "Rechargeable Battery 100W Pack", "cat": "Batteries & Power Systems", "cost": 950, "retail": 1700, "stock": 10, "serial": False},
            {"barcode": "CHG-BAT-150W", "name": "Rechargeable Battery 150W Heavy", "cat": "Batteries & Power Systems", "cost": 1400, "retail": 2500, "stock": 8, "serial": False},

            # 5. Storage Media
            {"barcode": "MEM-2GB", "name": "MicroSD Memory Card 2GB", "cat": "Storage Media", "cost": 150, "retail": 280, "stock": 20, "serial": False},
            {"barcode": "MEM-4GB", "name": "MicroSD Memory Card 4GB", "cat": "Storage Media", "cost": 180, "retail": 320, "stock": 25, "serial": False},
            {"barcode": "MEM-8GB", "name": "MicroSD Memory Card 8GB", "cat": "Storage Media", "cost": 220, "retail": 400, "stock": 30, "serial": False},
            {"barcode": "MEM-16GB", "name": "MicroSD Memory Card 16GB", "cat": "Storage Media", "cost": 300, "retail": 550, "stock": 35, "serial": False},
            {"barcode": "MEM-32GB", "name": "MicroSD Memory Card 32GB", "cat": "Storage Media", "cost": 450, "retail": 800, "stock": 30, "serial": False},
            {"barcode": "MEM-64GB", "name": "MicroSD Memory Card 64GB", "cat": "Storage Media", "cost": 800, "retail": 1400, "stock": 20, "serial": False},
            {"barcode": "FLSH-2GB", "name": "USB Flash Drive 2GB", "cat": "Storage Media", "cost": 180, "retail": 300, "stock": 20, "serial": False},
            {"barcode": "FLSH-4GB", "name": "USB Flash Drive 4GB", "cat": "Storage Media", "cost": 220, "retail": 380, "stock": 25, "serial": False},
            {"barcode": "FLSH-8GB", "name": "USB Flash Drive 8GB", "cat": "Storage Media", "cost": 280, "retail": 500, "stock": 30, "serial": False},
            {"barcode": "FLSH-16GB", "name": "USB Flash Drive 16GB", "cat": "Storage Media", "cost": 380, "retail": 650, "stock": 35, "serial": False},
            {"barcode": "FLSH-32GB", "name": "USB Flash Drive 32GB", "cat": "Storage Media", "cost": 500, "retail": 900, "stock": 30, "serial": False},
            {"barcode": "FLSH-64GB", "name": "USB Flash Drive 64GB", "cat": "Storage Media", "cost": 850, "retail": 1500, "stock": 25, "serial": False},
            {"barcode": "READ-CAR", "name": "Car Digital Card Reader", "cat": "Storage Media", "cost": 100, "retail": 200, "stock": 40, "serial": False},
            {"barcode": "READ-MEM", "name": "Multi-slot Memory Card Reader", "cat": "Storage Media", "cost": 80, "retail": 150, "stock": 50, "serial": False},

            # 6. Hardware & Hand Tools
            {"barcode": "HW-RAKE", "name": "Garden Rake Head Attachment", "cat": "Hardware & Hand Tools", "cost": 250, "retail": 400, "stock": 15, "serial": False},
            {"barcode": "HW-SLASHER", "name": "Grass Slasher Wooden Handle", "cat": "Hardware & Hand Tools", "cost": 300, "retail": 500, "stock": 12, "serial": False},
            {"barcode": "HW-HINGE-23L", "name": "Door Hinges No. 2/3 Light (Pair)", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 250, "stock": 30, "serial": False},
            {"barcode": "HW-HINGE-4H", "name": "Door Hinges No. 4 Heavy (Pair)", "cat": "Hardware & Hand Tools", "cost": 300, "retail": 500, "stock": 20, "serial": False},
            {"barcode": "HW-SAW-14", "name": "Handsaw 14-Inch Wooden Handle", "cat": "Hardware & Hand Tools", "cost": 400, "retail": 650, "stock": 10, "serial": False},
            {"barcode": "HW-ROLLER", "name": "Paint Roller Brush 9-Inch", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 280, "stock": 25, "serial": False},
            {"barcode": "HW-PLUMB", "name": "Masonry Plumb Bob Steel", "cat": "Hardware & Hand Tools", "cost": 200, "retail": 350, "stock": 15, "serial": False},
            {"barcode": "HW-HOSE-12", "name": "Gardening Hose Pipe 1/2-Inch x 60m", "cat": "Hardware & Hand Tools", "cost": 1800, "retail": 3000, "stock": 5, "serial": False},
            {"barcode": "TL-SPAN-R1617", "name": "Ring Spanner 16-17 Double Ended", "cat": "Hardware & Hand Tools", "cost": 200, "retail": 350, "stock": 15, "serial": False},
            {"barcode": "TL-SPAN-R1213", "name": "Ring Spanner 12-13 Double Ended", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 250, "stock": 15, "serial": False},
            {"barcode": "TL-SPAN-O1213", "name": "Open Ended Spanner 12-13", "cat": "Hardware & Hand Tools", "cost": 120, "retail": 200, "stock": 20, "serial": False},
            {"barcode": "TL-SPAN-O1617", "name": "Open Ended Spanner 16-17", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 250, "stock": 20, "serial": False},
            {"barcode": "TL-SPAN-O1819", "name": "Open Ended Spanner 18-19", "cat": "Hardware & Hand Tools", "cost": 180, "retail": 300, "stock": 15, "serial": False},
            {"barcode": "HW-BOLT-6", "name": "Konzi Tower Bolt 6-Inch", "cat": "Hardware & Hand Tools", "cost": 120, "retail": 220, "stock": 40, "serial": False},
            {"barcode": "HW-NAIL-2", "name": "Steel Nails 2-Inch (1kg Box)", "cat": "Hardware & Hand Tools", "cost": 180, "retail": 280, "stock": 30, "serial": False},
            {"barcode": "HW-NAIL-3", "name": "Steel Nails 3-Inch (1kg Box)", "cat": "Hardware & Hand Tools", "cost": 180, "retail": 280, "stock": 35, "serial": False},
            {"barcode": "HW-NAIL-4", "name": "Steel Nails 4-Inch (1kg Box)", "cat": "Hardware & Hand Tools", "cost": 180, "retail": 280, "stock": 30, "serial": False},
            {"barcode": "HW-CUTTER-B", "name": "Steel Nail Cutter (Big)", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 280, "stock": 20, "serial": False},
            {"barcode": "HW-CUTTER-S", "name": "Steel Nail Cutter (Small)", "cat": "Hardware & Hand Tools", "cost": 80, "retail": 150, "stock": 25, "serial": False},
            {"barcode": "TL-PLI-REDB", "name": "Red Combination Pliers (Big)", "cat": "Hardware & Hand Tools", "cost": 250, "retail": 450, "stock": 20, "serial": False},
            {"barcode": "TL-PLI-REDS", "name": "Red Combination Pliers (Small)", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 280, "stock": 25, "serial": False},
            {"barcode": "TL-PLI-ASTB", "name": "High Astra Pliers (Big)", "cat": "Hardware & Hand Tools", "cost": 300, "retail": 550, "stock": 15, "serial": False},
            {"barcode": "TL-PLI-ASTS", "name": "High Astra Pliers (Small)", "cat": "Hardware & Hand Tools", "cost": 200, "retail": 350, "stock": 15, "serial": False},
            {"barcode": "TL-PLI-ELEB", "name": "Insulated Electrical Pliers (Big)", "cat": "Hardware & Hand Tools", "cost": 350, "retail": 600, "stock": 15, "serial": False},
            {"barcode": "TL-PLI-ELES", "name": "Insulated Electrical Pliers (Small)", "cat": "Hardware & Hand Tools", "cost": 220, "retail": 400, "stock": 20, "serial": False},
            {"barcode": "TL-PLI-LNOB", "name": "Long Nose Pliers (Big)", "cat": "Hardware & Hand Tools", "cost": 250, "retail": 450, "stock": 15, "serial": False},
            {"barcode": "TL-PLI-LNOS", "name": "Long Nose Pliers (Small)", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 280, "stock": 20, "serial": False},
            {"barcode": "TL-STRIPPER", "name": "Automatic Wire & Cable Stripper", "cat": "Hardware & Hand Tools", "cost": 500, "retail": 950, "stock": 10, "serial": False},
            {"barcode": "TL-SCREW-L", "name": "Screwdriver Long Flat/Star", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 250, "stock": 30, "serial": False},
            {"barcode": "TL-SCREW-M", "name": "Screwdriver Medium Flat/Star", "cat": "Hardware & Hand Tools", "cost": 100, "retail": 180, "stock": 40, "serial": False},
            {"barcode": "TL-SCREW-S", "name": "Screwdriver Small Flat/Star", "cat": "Hardware & Hand Tools", "cost": 70, "retail": 120, "stock": 40, "serial": False},
            {"barcode": "TL-SCREW-INSF", "name": "Insulated Flat Screwdriver", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 250, "stock": 25, "serial": False},
            {"barcode": "TL-SCREW-INSS", "name": "Insulated Star Screwdriver", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 250, "stock": 25, "serial": False},
            {"barcode": "TL-SCREW-2IN1", "name": "2-in-1 Double Screwdriver", "cat": "Hardware & Hand Tools", "cost": 180, "retail": 320, "stock": 30, "serial": False},
            {"barcode": "TL-SCREW-SHRT", "name": "Short Rubber Handle Screwdriver", "cat": "Hardware & Hand Tools", "cost": 100, "retail": 180, "stock": 20, "serial": False},
            {"barcode": "TL-SCREW-SET", "name": "Multi-bit Screwdriver Toolkit Set", "cat": "Hardware & Hand Tools", "cost": 850, "retail": 1500, "stock": 8, "serial": False},
            {"barcode": "TL-TAPE-3M", "name": "Steel Measuring Tape 3m", "cat": "Hardware & Hand Tools", "cost": 120, "retail": 220, "stock": 30, "serial": False},
            {"barcode": "TL-TAPE-5M", "name": "Steel Measuring Tape 5m", "cat": "Hardware & Hand Tools", "cost": 180, "retail": 300, "stock": 25, "serial": False},
            {"barcode": "TL-TAPE-75M", "name": "Steel Measuring Tape 7.5m", "cat": "Hardware & Hand Tools", "cost": 280, "retail": 450, "stock": 20, "serial": False},
            {"barcode": "TL-TAPE-30M", "name": "Fiberglass Measuring Tape 30m", "cat": "Hardware & Hand Tools", "cost": 950, "retail": 1600, "stock": 10, "serial": False},
            {"barcode": "PAD-ROL-40", "name": "Rollinson Padlock 40mm", "cat": "Hardware & Hand Tools", "cost": 220, "retail": 380, "stock": 25, "serial": False},
            {"barcode": "PAD-ROL-50", "name": "Rollinson Padlock 50mm", "cat": "Hardware & Hand Tools", "cost": 300, "retail": 500, "stock": 20, "serial": False},
            {"barcode": "PAD-ROL-60", "name": "Rollinson Padlock 60mm", "cat": "Hardware & Hand Tools", "cost": 380, "retail": 650, "stock": 20, "serial": False},
            {"barcode": "PAD-ROL-70", "name": "Rollinson Padlock 70mm", "cat": "Hardware & Hand Tools", "cost": 450, "retail": 780, "stock": 15, "serial": False},
            {"barcode": "PAD-STL-40", "name": "Stellar Brass Padlock 40mm", "cat": "Hardware & Hand Tools", "cost": 180, "retail": 300, "stock": 25, "serial": False},
            {"barcode": "PAD-STL-50", "name": "Stellar Brass Padlock 50mm", "cat": "Hardware & Hand Tools", "cost": 250, "retail": 420, "stock": 20, "serial": False},
            {"barcode": "PAD-STL-60", "name": "Stellar Brass Padlock 60mm", "cat": "Hardware & Hand Tools", "cost": 320, "retail": 550, "stock": 20, "serial": False},
            {"barcode": "PAD-STL-70", "name": "Stellar Brass Padlock 70mm", "cat": "Hardware & Hand Tools", "cost": 400, "retail": 680, "stock": 15, "serial": False},
            {"barcode": "PAD-MIN-B", "name": "Mindy Armoured Padlock (Big)", "cat": "Hardware & Hand Tools", "cost": 650, "retail": 1100, "stock": 10, "serial": False},
            {"barcode": "PAD-MIN-M", "name": "Mindy Armoured Padlock (Medium)", "cat": "Hardware & Hand Tools", "cost": 500, "retail": 850, "stock": 12, "serial": False},
            {"barcode": "PAD-MIN-S", "name": "Mindy Armoured Padlock (Small)", "cat": "Hardware & Hand Tools", "cost": 380, "retail": 650, "stock": 15, "serial": False},
            {"barcode": "PAD-KAH-B", "name": "Kahang Coloured Padlock (Big)", "cat": "Hardware & Hand Tools", "cost": 300, "retail": 550, "stock": 20, "serial": False},
            {"barcode": "PAD-KAH-M", "name": "Kahang Coloured Padlock (Medium)", "cat": "Hardware & Hand Tools", "cost": 220, "retail": 400, "stock": 20, "serial": False},
            {"barcode": "PAD-SLX-30", "name": "Solix Steel Padlock 30mm", "cat": "Hardware & Hand Tools", "cost": 120, "retail": 220, "stock": 30, "serial": False},
            {"barcode": "PAD-ONK-B", "name": "Onika Sachet Padlock (Big)", "cat": "Hardware & Hand Tools", "cost": 400, "retail": 700, "stock": 15, "serial": False},
            {"barcode": "PAD-ONK-M", "name": "Onika Sachet Padlock (Medium)", "cat": "Hardware & Hand Tools", "cost": 300, "retail": 500, "stock": 20, "serial": False},
            {"barcode": "PAD-SHN-45", "name": "Sheng Steel Padlock 45mm", "cat": "Hardware & Hand Tools", "cost": 200, "retail": 350, "stock": 25, "serial": False},
            {"barcode": "PAD-SHN-55", "name": "Sheng Steel Padlock 55mm", "cat": "Hardware & Hand Tools", "cost": 280, "retail": 480, "stock": 25, "serial": False},
            {"barcode": "PAD-YNG-363", "name": "Yongli Padlock Model 363", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 250, "stock": 30, "serial": False},
            {"barcode": "PAD-YNG-364", "name": "Yongli Padlock Model 364", "cat": "Hardware & Hand Tools", "cost": 200, "retail": 350, "stock": 30, "serial": False},
            {"barcode": "PAD-YNG-365", "name": "Yongli Padlock Model 365", "cat": "Hardware & Hand Tools", "cost": 250, "retail": 420, "stock": 20, "serial": False},
            {"barcode": "PAD-YNG-366", "name": "Yongli Padlock Model 366", "cat": "Hardware & Hand Tools", "cost": 300, "retail": 500, "stock": 20, "serial": False},
            {"barcode": "PAD-CIC-40", "name": "Cica Steel Padlock 40mm", "cat": "Hardware & Hand Tools", "cost": 180, "retail": 300, "stock": 25, "serial": False},
            {"barcode": "PAD-CIC-50", "name": "Cica Steel Padlock 50mm", "cat": "Hardware & Hand Tools", "cost": 240, "retail": 400, "stock": 25, "serial": False},
            {"barcode": "PAD-CIC-60", "name": "Cica Steel Padlock 60mm", "cat": "Hardware & Hand Tools", "cost": 300, "retail": 500, "stock": 20, "serial": False},
            {"barcode": "PAD-CIC-70", "name": "Cica Steel Padlock 70mm", "cat": "Hardware & Hand Tools", "cost": 380, "retail": 650, "stock": 15, "serial": False},
            {"barcode": "PAD-TRI-263", "name": "Tricyclic Padlock Model 263", "cat": "Hardware & Hand Tools", "cost": 150, "retail": 250, "stock": 30, "serial": False},
            {"barcode": "PAD-TRI-264", "name": "Tricyclic Padlock Model 264", "cat": "Hardware & Hand Tools", "cost": 200, "retail": 350, "stock": 30, "serial": False},
            {"barcode": "PAD-TRI-265", "name": "Tricyclic Padlock Model 265", "cat": "Hardware & Hand Tools", "cost": 250, "retail": 420, "stock": 20, "serial": False},
            {"barcode": "PAD-TRI-266", "name": "Tricyclic Padlock Model 266", "cat": "Hardware & Hand Tools", "cost": 300, "retail": 500, "stock": 20, "serial": False},
            {"barcode": "PAD-SLD-35", "name": "Solda Sachet Padlock 35mm", "cat": "Hardware & Hand Tools", "cost": 140, "retail": 250, "stock": 25, "serial": False},
            {"barcode": "PAD-SLD-45", "name": "Solda Sachet Padlock 45mm", "cat": "Hardware & Hand Tools", "cost": 200, "retail": 350, "stock": 25, "serial": False},
            {"barcode": "PAD-SLD-55", "name": "Solda Sachet Padlock 55mm", "cat": "Hardware & Hand Tools", "cost": 260, "retail": 450, "stock": 20, "serial": False},
            {"barcode": "PAD-AUD-40", "name": "Auddy Steel Padlock 40mm", "cat": "Hardware & Hand Tools", "cost": 160, "retail": 280, "stock": 30, "serial": False},
            {"barcode": "PAD-AUD-50", "name": "Auddy Steel Padlock 50mm", "cat": "Hardware & Hand Tools", "cost": 220, "retail": 380, "stock": 25, "serial": False},
            {"barcode": "PAD-AUD-60", "name": "Auddy Steel Padlock 60mm", "cat": "Hardware & Hand Tools", "cost": 280, "retail": 480, "stock": 20, "serial": False},

            # 7. Lighting & Torches
            {"barcode": "TOR-KM-H06U", "name": "Kamisafe KM-H06U LED Headlamp", "cat": "Lighting & Torches", "cost": 450, "retail": 800, "stock": 15, "serial": False},
            {"barcode": "TOR-KM-H07U", "name": "Kamisafe KM-H07U LED Headlamp", "cat": "Lighting & Torches", "cost": 480, "retail": 850, "stock": 15, "serial": False},
            {"barcode": "TOR-KM-7629", "name": "Kamisafe KM-7629U Rechargeable", "cat": "Lighting & Torches", "cost": 650, "retail": 1100, "stock": 12, "serial": False},
            {"barcode": "TOR-KM-7605", "name": "Kamisafe KM-7605 Rechargeable", "cat": "Lighting & Torches", "cost": 500, "retail": 900, "stock": 18, "serial": False},
            {"barcode": "TOR-KM-8916", "name": "Kamisafe KM-8916A Searchlight", "cat": "Lighting & Torches", "cost": 850, "retail": 1400, "stock": 10, "serial": False},
            {"barcode": "TOR-KM-7108", "name": "Kamisafe KM-7108 Hand Torch", "cat": "Lighting & Torches", "cost": 300, "retail": 550, "stock": 20, "serial": False},
            {"barcode": "TOR-DP-7307", "name": "DP LED Torch Model 7307", "cat": "Lighting & Torches", "cost": 350, "retail": 600, "stock": 20, "serial": False},
            {"barcode": "TOR-DP-7045B", "name": "DP Torch 7045B 75W Searchlight", "cat": "Lighting & Torches", "cost": 1500, "retail": 2400, "stock": 8, "serial": False},
            {"barcode": "TOR-ST-837L", "name": "Technical Torch ST-837L LED", "cat": "Lighting & Torches", "cost": 550, "retail": 950, "stock": 12, "serial": False},
            {"barcode": "TOR-KIG-1B", "name": "Kiguha 1-Battery LED Torch", "cat": "Lighting & Torches", "cost": 120, "retail": 220, "stock": 40, "serial": False},
            {"barcode": "TOR-KIG-2B", "name": "Kiguha Double Battery Torch", "cat": "Lighting & Torches", "cost": 200, "retail": 350, "stock": 30, "serial": False},
            {"barcode": "TOR-CAST-2AAA", "name": "Caston Torch 2AAA Compact", "cat": "Lighting & Torches", "cost": 150, "retail": 280, "stock": 35, "serial": False},
            {"barcode": "TOR-QJ-2020", "name": "USB QJ-2020 Hand Torch", "cat": "Lighting & Torches", "cost": 250, "retail": 450, "stock": 30, "serial": False},
            {"barcode": "TOR-FT-9992", "name": "Utility Torch FT-9992 LED", "cat": "Lighting & Torches", "cost": 400, "retail": 700, "stock": 25, "serial": False},
            {"barcode": "TOR-FT-9799", "name": "Utility Torch FT-9799 LED", "cat": "Lighting & Torches", "cost": 380, "retail": 680, "stock": 25, "serial": False},
            {"barcode": "TOR-QL-001", "name": "USB LED QL-001 Portable Light", "cat": "Lighting & Torches", "cost": 120, "retail": 220, "stock": 50, "serial": False},
            {"barcode": "TOR-HS-FS", "name": "Hisheen HS-FS Precision Torch", "cat": "Lighting & Torches", "cost": 600, "retail": 1000, "stock": 15, "serial": False},
            {"barcode": "TOR-HL-6504", "name": "Rechargeable Torch HL-6504", "cat": "Lighting & Torches", "cost": 500, "retail": 850, "stock": 15, "serial": False},
            {"barcode": "TOR-FT-309L", "name": "High Beam Torch FT-309L", "cat": "Lighting & Torches", "cost": 750, "retail": 1300, "stock": 10, "serial": False},
            {"barcode": "TOR-TH-5309", "name": "Heavy Duty Torch TH-5309", "cat": "Lighting & Torches", "cost": 800, "retail": 1400, "stock": 8, "serial": False},
            {"barcode": "TOR-TH-5050A", "name": "Heavy Duty Torch TH-5050A", "cat": "Lighting & Torches", "cost": 900, "retail": 1600, "stock": 8, "serial": False},
            {"barcode": "TOR-TBL-TB11", "name": "Aviation Torch TBL TB11", "cat": "Lighting & Torches", "cost": 1000, "retail": 1750, "stock": 6, "serial": False},
            {"barcode": "TOR-ST-245", "name": "LED Focus Torch ST-245", "cat": "Lighting & Torches", "cost": 350, "retail": 600, "stock": 25, "serial": False},
            {"barcode": "TOR-ST-5098A", "name": "LED Focus Torch ST-5098A", "cat": "Lighting & Torches", "cost": 450, "retail": 800, "stock": 20, "serial": False},
            {"barcode": "TOR-ST-918", "name": "LED Focus Torch ST-918 (Small)", "cat": "Lighting & Torches", "cost": 200, "retail": 350, "stock": 35, "serial": False},
            {"barcode": "TOR-TH-5155", "name": "Tactical Torch TH-5155 LED", "cat": "Lighting & Torches", "cost": 650, "retail": 1100, "stock": 15, "serial": False},
            {"barcode": "BLB-KM-5819", "name": "Kamisafe Emergency Bulb 5819A", "cat": "Lighting & Torches", "cost": 350, "retail": 650, "stock": 20, "serial": False},
            {"barcode": "BLB-NEE-5WS", "name": "Neelux LED Screw Bulb 5W", "cat": "Lighting & Torches", "cost": 120, "retail": 220, "stock": 60, "serial": False},
            {"barcode": "BLB-TRO-20W", "name": "Tronic LED Bulb 20W E27", "cat": "Lighting & Torches", "cost": 280, "retail": 480, "stock": 40, "serial": False},
            {"barcode": "BLB-TRO-5W", "name": "Tronic LED Bulb 5W E27", "cat": "Lighting & Torches", "cost": 110, "retail": 200, "stock": 50, "serial": False},
            {"barcode": "BLB-DP-AC3W", "name": "DP AC LED Bulb 3W", "cat": "Lighting & Torches", "cost": 90, "retail": 180, "stock": 60, "serial": False},
            {"barcode": "BLB-DP-AC5W", "name": "DP AC LED Bulb 5W", "cat": "Lighting & Torches", "cost": 120, "retail": 220, "stock": 60, "serial": False},
            {"barcode": "BLB-DP-AC7W", "name": "DP AC LED Bulb 7W", "cat": "Lighting & Torches", "cost": 150, "retail": 280, "stock": 55, "serial": False},
            {"barcode": "BLB-DP-DC3W", "name": "DP DC Solar Bulb 3W", "cat": "Lighting & Torches", "cost": 110, "retail": 200, "stock": 45, "serial": False},
            {"barcode": "BLB-DP-DC5W", "name": "DP DC Solar Bulb 5W", "cat": "Lighting & Torches", "cost": 140, "retail": 250, "stock": 40, "serial": False},
            {"barcode": "BLB-DP-DC7W", "name": "DP DC Solar Bulb 7W", "cat": "Lighting & Torches", "cost": 180, "retail": 320, "stock": 35, "serial": False},
            {"barcode": "BLB-NEE-5W", "name": "Neelux LED Pin Bulb 5W", "cat": "Lighting & Torches", "cost": 120, "retail": 220, "stock": 60, "serial": False},
            {"barcode": "BLB-NEE-7W", "name": "Neelux LED Pin Bulb 7W", "cat": "Lighting & Torches", "cost": 150, "retail": 280, "stock": 50, "serial": False},
            {"barcode": "BLB-CUP-18W", "name": "Cup LED Ceiling Bulb 18W", "cat": "Lighting & Torches", "cost": 300, "retail": 550, "stock": 25, "serial": False},
            {"barcode": "BLB-CUP-24W", "name": "Cup LED Ceiling Bulb 24W", "cat": "Lighting & Torches", "cost": 380, "retail": 700, "stock": 25, "serial": False},
            {"barcode": "BLB-CUP-40W", "name": "Cup LED Ceiling Bulb 40W", "cat": "Lighting & Torches", "cost": 550, "retail": 950, "stock": 20, "serial": False},
            {"barcode": "BLB-PLT-15W", "name": "Plate LED Surface Bulb 15W", "cat": "Lighting & Torches", "cost": 250, "retail": 450, "stock": 30, "serial": False},
            {"barcode": "BLB-PLT-18W", "name": "Plate LED Surface Bulb 18W", "cat": "Lighting & Torches", "cost": 300, "retail": 550, "stock": 30, "serial": False},
            {"barcode": "BLB-PLT-24W", "name": "Plate LED Surface Bulb 24W", "cat": "Lighting & Torches", "cost": 380, "retail": 700, "stock": 25, "serial": False},
            {"barcode": "BLB-PLT-36W", "name": "Plate LED Surface Bulb 36W", "cat": "Lighting & Torches", "cost": 500, "retail": 900, "stock": 20, "serial": False},
            {"barcode": "BLB-AVC-CLR", "name": "AVC Clear Incandescent Bulb", "cat": "Lighting & Torches", "cost": 50, "retail": 100, "stock": 100, "serial": False},
            {"barcode": "BLB-AVC-COL", "name": "AVC Coloured Party Bulb", "cat": "Lighting & Torches", "cost": 60, "retail": 120, "stock": 80, "serial": False},
            {"barcode": "BLB-AVC-3IN1", "name": "AVC 3-in-1 Smart LED Bulb", "cat": "Lighting & Torches", "cost": 250, "retail": 450, "stock": 30, "serial": False},
            {"barcode": "BLB-VET-3IN1", "name": "Vettmax 3-in-1 LED Bulb", "cat": "Lighting & Torches", "cost": 220, "retail": 400, "stock": 35, "serial": False},
            {"barcode": "BLB-TROP-60W", "name": "Tropical Filament Bulb 60W", "cat": "Lighting & Torches", "cost": 50, "retail": 100, "stock": 60, "serial": False},
            {"barcode": "BLB-TROP-75W", "name": "Tropical Filament Bulb 75W", "cat": "Lighting & Torches", "cost": 50, "retail": 100, "stock": 60, "serial": False},
            {"barcode": "BLB-TROP-100W", "name": "Tropical Filament Bulb 100W", "cat": "Lighting & Torches", "cost": 50, "retail": 100, "stock": 60, "serial": False},
            {"barcode": "BLB-TUBE-T8", "name": "DC Solar Tube T8 4FT", "cat": "Lighting & Torches", "cost": 300, "retail": 550, "stock": 30, "serial": False},
            {"barcode": "BLB-TUBE-JIN", "name": "DC Solar Tube Jin Brand 2FT", "cat": "Lighting & Torches", "cost": 200, "retail": 380, "stock": 30, "serial": False},
            {"barcode": "BLB-PAWA-75W", "name": "Pawa High-Power LED Bulb 75W", "cat": "Lighting & Torches", "cost": 900, "retail": 1600, "stock": 10, "serial": False},
            {"barcode": "BLB-PAWA-100W", "name": "Pawa High-Power LED Bulb 100W", "cat": "Lighting & Torches", "cost": 1200, "retail": 2000, "stock": 10, "serial": False},
            {"barcode": "FLD-AC-10W", "name": "AC Outdoor Floodlight 10W IP65", "cat": "Lighting & Torches", "cost": 500, "retail": 900, "stock": 15, "serial": False},
            {"barcode": "FLD-AC-20W", "name": "AC Outdoor Floodlight 20W IP65", "cat": "Lighting & Torches", "cost": 800, "retail": 1400, "stock": 12, "serial": False},
            {"barcode": "FLD-AC-30W", "name": "AC Outdoor Floodlight 30W IP65", "cat": "Lighting & Torches", "cost": 1200, "retail": 2000, "stock": 10, "serial": False},
            {"barcode": "FLD-DC-10W", "name": "DC Solar Floodlight 10W Kit", "cat": "Lighting & Torches", "cost": 800, "retail": 1500, "stock": 10, "serial": False},
            {"barcode": "FLD-DC-20W", "name": "DC Solar Floodlight 20W Kit", "cat": "Lighting & Torches", "cost": 1400, "retail": 2500, "stock": 8, "serial": False},
            {"barcode": "FLD-DC-30W", "name": "DC Solar Floodlight 30W Kit", "cat": "Lighting & Torches", "cost": 2000, "retail": 3500, "stock": 5, "serial": False},
            {"barcode": "TUBE-4FT-GLS", "name": "Normal 4FT Glass LED Tube", "cat": "Lighting & Torches", "cost": 120, "retail": 250, "stock": 40, "serial": False},
            {"barcode": "TUBE-2FT-GLS", "name": "Normal 2FT Glass LED Tube", "cat": "Lighting & Torches", "cost": 100, "retail": 200, "stock": 45, "serial": False},
            {"barcode": "TUBE-4FT-PLS", "name": "Plastic LED Energy Saver 4FT", "cat": "Lighting & Torches", "cost": 150, "retail": 300, "stock": 50, "serial": False},
            {"barcode": "TUBE-2FT-PLS", "name": "Plastic LED Energy Saver 2FT", "cat": "Lighting & Torches", "cost": 120, "retail": 240, "stock": 50, "serial": False},
            {"barcode": "FIX-4FT-NORM", "name": "LED Tube Fixture Batten 4FT", "cat": "Lighting & Torches", "cost": 150, "retail": 280, "stock": 40, "serial": False},
            {"barcode": "FIX-2FT-NORM", "name": "LED Tube Fixture Batten 2FT", "cat": "Lighting & Torches", "cost": 120, "retail": 220, "stock": 40, "serial": False},
            {"barcode": "XMAS-DEC-LIG", "name": "Xmas Decoration LED Light Chain", "cat": "Lighting & Torches", "cost": 250, "retail": 450, "stock": 50, "serial": False},
            {"barcode": "XMAS-REMOTE", "name": "Xmas Light Controller Remote", "cat": "Lighting & Torches", "cost": 100, "retail": 200, "stock": 40, "serial": False},
            {"barcode": "XMAS-SNAKE-5M", "name": "Flexible Snake Neon Light 5m", "cat": "Lighting & Torches", "cost": 650, "retail": 1200, "stock": 15, "serial": False},
            {"barcode": "XMAS-SNAKE-10M", "name": "Flexible Snake Neon Light 10m", "cat": "Lighting & Torches", "cost": 1100, "retail": 2000, "stock": 15, "serial": False},

            # 8. Electrical Fittings & Switches
            {"barcode": "EXT-BAB-AST", "name": "BAB Astra Extension 4-Way", "cat": "Electrical Fittings & Switches", "cost": 650, "retail": 1100, "stock": 12, "serial": False},
            {"barcode": "EXT-BLACK-3W", "name": "Universal Extension Black 3-Way", "cat": "Electrical Fittings & Switches", "cost": 300, "retail": 550, "stock": 20, "serial": False},
            {"barcode": "EXT-PK-BLUE", "name": "Power King Extension Blue 5-Way", "cat": "Electrical Fittings & Switches", "cost": 500, "retail": 850, "stock": 15, "serial": False},
            {"barcode": "EXT-JSB-4W", "name": "JSB Extension Socket 4-Way", "cat": "Electrical Fittings & Switches", "cost": 450, "retail": 750, "stock": 20, "serial": False},
            {"barcode": "EXT-JSB-5W", "name": "JSB Extension Socket 5-Way", "cat": "Electrical Fittings & Switches", "cost": 500, "retail": 850, "stock": 18, "serial": False},
            {"barcode": "EXT-JSB-6W", "name": "JSB Extension Socket 6-Way", "cat": "Electrical Fittings & Switches", "cost": 550, "retail": 950, "stock": 15, "serial": False},
            {"barcode": "EXT-CAST-4W", "name": "Caston Heavy Extension 4-Way", "cat": "Electrical Fittings & Switches", "cost": 700, "retail": 1200, "stock": 10, "serial": False},
            {"barcode": "EXT-RG-BLK", "name": "Royal Gold Extension (Black)", "cat": "Electrical Fittings & Switches", "cost": 600, "retail": 1000, "stock": 12, "serial": False},
            {"barcode": "EXT-MAR-5W", "name": "Marken extension Cable 5-Way", "cat": "Electrical Fittings & Switches", "cost": 480, "retail": 800, "stock": 15, "serial": False},
            {"barcode": "FIT-SW-EXT", "name": "Bed Switch with Lead Extension", "cat": "Electrical Fittings & Switches", "cost": 150, "retail": 280, "stock": 30, "serial": False},
            {"barcode": "FIT-SW-NOEXT", "name": "Bed Switch without Extension", "cat": "Electrical Fittings & Switches", "cost": 80, "retail": 150, "stock": 40, "serial": False},
            {"barcode": "EXT-PK-1004", "name": "Power King Extension PK 1004", "cat": "Electrical Fittings & Switches", "cost": 350, "retail": 600, "stock": 20, "serial": False},
            {"barcode": "EXT-PK-1005", "name": "Power King Extension PK 1005", "cat": "Electrical Fittings & Switches", "cost": 400, "retail": 700, "stock": 20, "serial": False},
            {"barcode": "EXT-PK-1006", "name": "Power King Extension PK 1006", "cat": "Electrical Fittings & Switches", "cost": 450, "retail": 800, "stock": 15, "serial": False},
            {"barcode": "EXT-USB-AST", "name": "Astra Extension with USB ports", "cat": "Electrical Fittings & Switches", "cost": 800, "retail": 1400, "stock": 12, "serial": False},
            {"barcode": "FIT-HLD-STB", "name": "Straight Bulb Holder (Big)", "cat": "Electrical Fittings & Switches", "cost": 40, "retail": 80, "stock": 100, "serial": False},
            {"barcode": "FIT-HLD-STS", "name": "Straight Bulb Holder (Small)", "cat": "Electrical Fittings & Switches", "cost": 30, "retail": 60, "stock": 100, "serial": False},
            {"barcode": "FIT-HLD-ANB", "name": "Angle Bulb Holder (Big)", "cat": "Electrical Fittings & Switches", "cost": 50, "retail": 100, "stock": 80, "serial": False},
            {"barcode": "FIT-HLD-ANS", "name": "Angle Bulb Holder (Small)", "cat": "Electrical Fittings & Switches", "cost": 40, "retail": 80, "stock": 80, "serial": False},
            {"barcode": "FIT-HLD-HANG", "name": "Hanging Bulb Holder Socket", "cat": "Electrical Fittings & Switches", "cost": 40, "retail": 80, "stock": 120, "serial": False},
            {"barcode": "FIT-HLD-SCRW", "name": "Screw Type Bulb Holder E27", "cat": "Electrical Fittings & Switches", "cost": 50, "retail": 100, "stock": 90, "serial": False},
            {"barcode": "FIT-CEIL-ROSE", "name": "Ceiling Rose Base Plate Fitting", "cat": "Electrical Fittings & Switches", "cost": 60, "retail": 120, "stock": 70, "serial": False},
            {"barcode": "SW-1G-PRIME", "name": "1-Gang Switch Prime Range", "cat": "Electrical Fittings & Switches", "cost": 150, "retail": 280, "stock": 45, "serial": False},
            {"barcode": "SW-1G-RPR", "name": "1-Gang Switch RP Royalty", "cat": "Electrical Fittings & Switches", "cost": 180, "retail": 320, "stock": 40, "serial": False},
            {"barcode": "SW-SHOWER", "name": "Heavy-Duty Instant Shower Switch", "cat": "Electrical Fittings & Switches", "cost": 350, "retail": 600, "stock": 25, "serial": False},
            {"barcode": "SW-1G-WINDS", "name": "1-Gang Switch Windsor Classic", "cat": "Electrical Fittings & Switches", "cost": 160, "retail": 300, "stock": 35, "serial": False},
            {"barcode": "SW-DP-LIGHT", "name": "DP Light Switch Plate", "cat": "Electrical Fittings & Switches", "cost": 180, "retail": 320, "stock": 30, "serial": False},
            {"barcode": "SW-2G-DPL", "name": "2-Gang Switch DP Light Range", "cat": "Electrical Fittings & Switches", "cost": 220, "retail": 380, "stock": 30, "serial": False},
            {"barcode": "SW-2G-RPR", "name": "2-Gang Switch RP Royalty Range", "cat": "Electrical Fittings & Switches", "cost": 250, "retail": 420, "stock": 25, "serial": False},
            {"barcode": "SW-2G-HGM", "name": "2-Gang Switch HG Memorius Range", "cat": "Electrical Fittings & Switches", "cost": 280, "retail": 480, "stock": 20, "serial": False},
            {"barcode": "FIT-CLIP-9MM", "name": "Cable Clips 9mm (100pcs Packet)", "cat": "Electrical Fittings & Switches", "cost": 80, "retail": 150, "stock": 60, "serial": False},
            {"barcode": "FIT-CLIP-12MM", "name": "Cable Clips 12mm (100pcs Packet)", "cat": "Electrical Fittings & Switches", "cost": 100, "retail": 180, "stock": 50, "serial": False},
            {"barcode": "SOC-1G-DPL", "name": "Single Socket 13A DP Light", "cat": "Electrical Fittings & Switches", "cost": 200, "retail": 350, "stock": 30, "serial": False},
            {"barcode": "SOC-1G-RPR", "name": "Single Socket 13A RP Royalty", "cat": "Electrical Fittings & Switches", "cost": 240, "retail": 400, "stock": 30, "serial": False},
            {"barcode": "SOC-2G-RPR", "name": "Double Socket 2-Gang RP Royalty", "cat": "Electrical Fittings & Switches", "cost": 350, "retail": 600, "stock": 25, "serial": False},
            {"barcode": "SOC-COOKER", "name": "Cooker Control Unit Socket", "cat": "Electrical Fittings & Switches", "cost": 450, "retail": 800, "stock": 15, "serial": False},
            {"barcode": "SOC-INDUST", "name": "Industrial Socket Outlets 16A/32A", "cat": "Electrical Fittings & Switches", "cost": 650, "retail": 1100, "stock": 10, "serial": False},
            {"barcode": "PLG-TOPNEXU", "name": "Topnexu 13A Square Pin Plug Top", "cat": "Electrical Fittings & Switches", "cost": 60, "retail": 120, "stock": 80, "serial": False},
            {"barcode": "PLG-BLACK-13A", "name": "Standard Black 13A Plug Top", "cat": "Electrical Fittings & Switches", "cost": 50, "retail": 100, "stock": 100, "serial": False},
            {"barcode": "PLG-MULTI-B", "name": "Multi-way Socket Plug Adapter (Big)", "cat": "Electrical Fittings & Switches", "cost": 120, "retail": 220, "stock": 40, "serial": False},
            {"barcode": "PLG-MULTI-S", "name": "Multi-way Socket Plug Adapt (Small)", "cat": "Electrical Fittings & Switches", "cost": 80, "retail": 150, "stock": 50, "serial": False},
            {"barcode": "FIT-JB-SM", "name": "Joint Box Round PVC (Small)", "cat": "Electrical Fittings & Switches", "cost": 30, "retail": 60, "stock": 90, "serial": False},
            {"barcode": "FIT-JB-BG", "name": "Joint Box Round PVC (Big)", "cat": "Electrical Fittings & Switches", "cost": 50, "retail": 100, "stock": 70, "serial": False},
            {"barcode": "CON-20MM", "name": "PVC Conduit Pipe 20mm (3m Link)", "cat": "Electrical Fittings & Switches", "cost": 110, "retail": 200, "stock": 150, "serial": False},
            {"barcode": "TRK-2010", "name": "PVC Mini Trunking 20x10mm (3m)", "cat": "Electrical Fittings & Switches", "cost": 130, "retail": 220, "stock": 120, "serial": False},
            {"barcode": "FIT-BOX-TWIN", "name": "Switch Metal Box Double (Twin)", "cat": "Electrical Fittings & Switches", "cost": 80, "retail": 150, "stock": 60, "serial": False},
            {"barcode": "FIT-BOX-SING", "name": "Switch Metal Box Single (1-Gang)", "cat": "Electrical Fittings & Switches", "cost": 50, "retail": 100, "stock": 80, "serial": False},
            {"barcode": "FIT-BOX-CIRC", "name": "Switch Box Circular PVC Pattern", "cat": "Electrical Fittings & Switches", "cost": 40, "retail": 80, "stock": 90, "serial": False},
            {"barcode": "FIT-PAT-SING", "name": "Single Surface Patress Box PVC", "cat": "Electrical Fittings & Switches", "cost": 60, "retail": 120, "stock": 50, "serial": False},
            {"barcode": "FIT-PAT-DBL", "name": "Double Surface Patress Box PVC", "cat": "Electrical Fittings & Switches", "cost": 100, "retail": 180, "stock": 40, "serial": False},
            {"barcode": "FIT-COV-SING", "name": "Patress Cover Single Plate blank", "cat": "Electrical Fittings & Switches", "cost": 30, "retail": 60, "stock": 60, "serial": False},
            {"barcode": "FIT-COV-DBL", "name": "Patress Cover Double Plate blank", "cat": "Electrical Fittings & Switches", "cost": 50, "retail": 100, "stock": 50, "serial": False},
            {"barcode": "FIT-TAPE-SUNUP", "name": "Sunup PVC Insulation Tape", "cat": "Electrical Fittings & Switches", "cost": 40, "retail": 80, "stock": 150, "serial": False},
            {"barcode": "FIT-TAPE-GLOBE", "name": "Globe PVC Insulation Tape Standard", "cat": "Electrical Fittings & Switches", "cost": 30, "retail": 60, "stock": 200, "serial": False},
            {"barcode": "FIT-TAPE-GLOBEB", "name": "Globe PVC Insulation Tape (Big)", "cat": "Electrical Fittings & Switches", "cost": 60, "retail": 120, "stock": 100, "serial": False},
            {"barcode": "FIT-GLUE-ALT", "name": "Alteco Super Glue 3G Tube", "cat": "Electrical Fittings & Switches", "cost": 40, "retail": 80, "stock": 120, "serial": False},
            {"barcode": "FIT-SIL-15G", "name": "Silicone Adhesive Glue 15G", "cat": "Electrical Fittings & Switches", "cost": 100, "retail": 200, "stock": 40, "serial": False},
            {"barcode": "FIT-SIL-TUBE", "name": "Silicone Sealant Clear Tube Big", "cat": "Electrical Fittings & Switches", "cost": 350, "retail": 600, "stock": 20, "serial": False},
            {"barcode": "FIT-LMGELL", "name": "LMGell Glue Adhesive Compound", "cat": "Electrical Fittings & Switches", "cost": 250, "retail": 450, "stock": 20, "serial": False},
            {"barcode": "FIT-ARALDITE", "name": "Araldite Epoxy Steel Adhesive", "cat": "Electrical Fittings & Switches", "cost": 380, "retail": 650, "stock": 15, "serial": False},
            {"barcode": "FIT-THREAD", "name": "Thread Teflon Tape (Water/Steam)", "cat": "Electrical Fittings & Switches", "cost": 30, "retail": 60, "stock": 150, "serial": False},
            {"barcode": "CCU-SINGLE", "name": "Consumer Unit Box Single Phase", "cat": "Electrical Fittings & Switches", "cost": 2800, "retail": 4500, "stock": 3, "serial": True, "serials": "CCUSG-001,CCUSG-002,CCUSG-003"},
            {"barcode": "CCU-CRAB", "name": "CCU Crab Switch Controller", "cat": "Electrical Fittings & Switches", "cost": 650, "retail": 1200, "stock": 10, "serial": False},
            {"barcode": "CCU-MAIN", "name": "CCU Main Isolator Switch 100A", "cat": "Electrical Fittings & Switches", "cost": 1200, "retail": 2000, "stock": 5, "serial": False},
            {"barcode": "SW-MAIN-OUT", "name": "Main Isolator Switch Outwards", "cat": "Electrical Fittings & Switches", "cost": 1500, "retail": 2500, "stock": 4, "serial": False},
            {"barcode": "DB-EURO-2W", "name": "Europlus Distribution Board 2-Way", "cat": "Electrical Fittings & Switches", "cost": 1800, "retail": 3000, "stock": 5, "serial": False},
            {"barcode": "FIT-SANDAL-CL", "name": "Sandal Plastic Cable Clips Pack", "cat": "Electrical Fittings & Switches", "cost": 120, "retail": 250, "stock": 40, "serial": False},
            {"barcode": "FIT-BENT-20", "name": "PVC Conduit Bent 20mm", "cat": "Electrical Fittings & Switches", "cost": 40, "retail": 80, "stock": 90, "serial": False},
            {"barcode": "FIT-BENT-25", "name": "PVC Conduit Bent 25mm", "cat": "Electrical Fittings & Switches", "cost": 60, "retail": 120, "stock": 70, "serial": False},
            {"barcode": "FIT-MBOX-B", "name": "Metal Box Deep Pattern (Big)", "cat": "Electrical Fittings & Switches", "cost": 120, "retail": 220, "stock": 50, "serial": False},
            {"barcode": "FIT-MBOX-S", "name": "Metal Box Deep Pattern (Small)", "cat": "Electrical Fittings & Switches", "cost": 80, "retail": 150, "stock": 60, "serial": False},
            {"barcode": "FIT-CRABTREE", "name": "Crabtree Grid Switch Plate", "cat": "Electrical Fittings & Switches", "cost": 250, "retail": 450, "stock": 25, "serial": False},
            {"barcode": "FIT-CHOKE", "name": "Fluorescent Choke Starter", "cat": "Electrical Fittings & Switches", "cost": 50, "retail": 100, "stock": 80, "serial": False},
            {"barcode": "FIT-EROD-B", "name": "Earth Rod Copper Bonded (Big)", "cat": "Electrical Fittings & Switches", "cost": 1200, "retail": 2000, "stock": 5, "serial": False},
            {"barcode": "FIT-EROD-S", "name": "Earth Rod Copper Bonded (Small)", "cat": "Electrical Fittings & Switches", "cost": 800, "retail": 1400, "stock": 8, "serial": False},
            {"barcode": "FIT-RAIL-F", "name": "Din Mounting Rail Steel (Full Link)", "cat": "Electrical Fittings & Switches", "cost": 300, "retail": 550, "stock": 10, "serial": False},
            {"barcode": "FIT-RAIL-H", "name": "Din Mounting Rail Steel (Half Link)", "cat": "Electrical Fittings & Switches", "cost": 180, "retail": 320, "stock": 15, "serial": False},
            {"barcode": "FIT-CUTOUT-S", "name": "Cut Out Fuse Single Unit", "cat": "Electrical Fittings & Switches", "cost": 350, "retail": 650, "stock": 12, "serial": False},
            {"barcode": "FIT-MCB-SP", "name": "Miniature Circuit Breaker Single Pole", "cat": "Electrical Fittings & Switches", "cost": 450, "retail": 800, "stock": 20, "serial": False},
            {"barcode": "FIT-MCB-DP", "name": "Miniature Circuit Breaker Double Pole", "cat": "Electrical Fittings & Switches", "cost": 850, "retail": 1500, "stock": 15, "serial": False},
            {"barcode": "FIT-SCREW-GYP", "name": "Gypsum Screws Box 1-Inch", "cat": "Electrical Fittings & Switches", "cost": 350, "retail": 600, "stock": 20, "serial": False},
            {"barcode": "FIT-SCREW-WD", "name": "Wooden Screws Box 1.5-Inch", "cat": "Electrical Fittings & Switches", "cost": 400, "retail": 700, "stock": 20, "serial": False},
            {"barcode": "FIT-SCREW-4MM", "name": "Machine Screws 4mm Thread Pack", "cat": "Electrical Fittings & Switches", "cost": 150, "retail": 300, "stock": 35, "serial": False},
            {"barcode": "FIT-TYR-B", "name": "Cable Ties Tyrup (Pack of 100 Big)", "cat": "Electrical Fittings & Switches", "cost": 250, "retail": 450, "stock": 30, "serial": False},
            {"barcode": "FIT-TYR-S", "name": "Cable Ties Tyrup (Pack of 100 Small)", "cat": "Electrical Fittings & Switches", "cost": 120, "retail": 250, "stock": 40, "serial": False},
            {"barcode": "FIT-SACK-90", "name": "Sack Packaging bags 90 kgs", "cat": "Electrical Fittings & Switches", "cost": 100, "retail": 200, "stock": 50, "serial": False},

            # 9. Electronics & Small Appliances
            {"barcode": "APP-WAHL-CLIP", "name": "Wahl Professional Hair Clipper", "cat": "Electronics & Small Appliances", "cost": 2800, "retail": 4500, "stock": 3, "serial": True, "serials": "WHLCLP-001,WHLCLP-002,WHLCLP-003"},
            {"barcode": "APP-CLR-CLIP", "name": "Kinyozi Hair Clipper Clear Range", "cat": "Electronics & Small Appliances", "cost": 1800, "retail": 3000, "stock": 4, "serial": True, "serials": "CLRCLP-001,CLRCLP-002,CLRCLP-003,CLRCLP-004"},
            {"barcode": "APP-WAHL-BLD", "name": "Wahl Clipper Taper Blade", "cat": "Electronics & Small Appliances", "cost": 500, "retail": 950, "stock": 10, "serial": False},
            {"barcode": "APP-STARWEX", "name": "Star Wex Hair Gel Wax", "cat": "Electronics & Small Appliances", "cost": 150, "retail": 300, "stock": 25, "serial": False},
            {"barcode": "APP-GOTV-DEC", "name": "Go TV Decoder with Remote & Cable", "cat": "Electronics & Small Appliances", "cost": 1500, "retail": 2500, "stock": 5, "serial": True, "serials": "GOTVDEC-101,GOTVDEC-102,GOTVDEC-103,GOTVDEC-104,GOTVDEC-105"},
            {"barcode": "APP-SIG-FIND", "name": "Satellite Signal Finder Meter", "cat": "Electronics & Small Appliances", "cost": 1200, "retail": 2000, "stock": 4, "serial": False},
            {"barcode": "APP-SAM-DVD", "name": "Samsung DVD Multi-Player", "cat": "Electronics & Small Appliances", "cost": 2500, "retail": 4000, "stock": 2, "serial": True, "serials": "SAMDVD-001,SAMDVD-002"},
            {"barcode": "APP-SONY-DVD", "name": "Sony DVD Multi-Player HDMI", "cat": "Electronics & Small Appliances", "cost": 3000, "retail": 4800, "stock": 2, "serial": True, "serials": "SNYDVD-091,SNYDVD-092"},
            {"barcode": "APP-IRON", "name": "Dry Electric Iron Box", "cat": "Electronics & Small Appliances", "cost": 1100, "retail": 1800, "stock": 6, "serial": False},
            {"barcode": "APP-FRASEN", "name": "Frasen Power Voltage Guard", "cat": "Electronics & Small Appliances", "cost": 850, "retail": 1500, "stock": 10, "serial": False},
            {"barcode": "APP-GEK3800", "name": "Super Energy Gek3800 Voltage Guard", "cat": "Electronics & Small Appliances", "cost": 1000, "retail": 1800, "stock": 8, "serial": False},
            {"barcode": "APP-SWATTER", "name": "Electric Rechargeable Mosquito Swatter", "cat": "Electronics & Small Appliances", "cost": 300, "retail": 550, "stock": 15, "serial": False},
            {"barcode": "APP-HEAT-B", "name": "Water Immersion Heater Black (Big)", "cat": "Electronics & Small Appliances", "cost": 400, "retail": 750, "stock": 15, "serial": False},
            {"barcode": "APP-HEAT-G", "name": "Water Immersion Heater Green", "cat": "Electronics & Small Appliances", "cost": 250, "retail": 450, "stock": 20, "serial": False},
            {"barcode": "APP-HEAT-R", "name": "Water Immersion Heater Red", "cat": "Electronics & Small Appliances", "cost": 250, "retail": 450, "stock": 20, "serial": False},
            {"barcode": "APP-HEAT-COF", "name": "Water Immersion Heater Coffee size", "cat": "Electronics & Small Appliances", "cost": 150, "retail": 300, "stock": 25, "serial": False},
            {"barcode": "TL-TESTER", "name": "Voltage Electrical Tester Pen", "cat": "Electronics & Small Appliances", "cost": 80, "retail": 150, "stock": 50, "serial": False},
            {"barcode": "TL-TESTER-COL", "name": "Voltage Electrical Tester Coloured", "cat": "Electronics & Small Appliances", "cost": 100, "retail": 180, "stock": 45, "serial": False},
            {"barcode": "GAS-REG-GR18", "name": "Gas Burner Regulator GR-18", "cat": "Electronics & Small Appliances", "cost": 450, "retail": 800, "stock": 15, "serial": False},
            {"barcode": "GAS-BURN-PRIM", "name": "Gas Burner Primus Attachment", "cat": "Electronics & Small Appliances", "cost": 350, "retail": 600, "stock": 20, "serial": False},
            {"barcode": "GAS-BURN-HR", "name": "Gas Burner HR High Pressure", "cat": "Electronics & Small Appliances", "cost": 500, "retail": 900, "stock": 15, "serial": False},
            {"barcode": "GAS-BURN-ORG3", "name": "Gas Burner Orgaz 3 Ring", "cat": "Electronics & Small Appliances", "cost": 900, "retail": 1500, "stock": 10, "serial": False},
            {"barcode": "HW-SHOWER-HD", "name": "Salty Water Instant Shower Head", "cat": "Electronics & Small Appliances", "cost": 1500, "retail": 2800, "stock": 8, "serial": False},
            {"barcode": "HW-BAT-CLPM", "name": "Battery Terminal Clips Mono (Pair)", "cat": "Electronics & Small Appliances", "cost": 120, "retail": 220, "stock": 30, "serial": False},
            {"barcode": "HW-BAT-CLPS", "name": "Battery Terminal Clips Star (Pair)", "cat": "Electronics & Small Appliances", "cost": 150, "retail": 280, "stock": 25, "serial": False},
            {"barcode": "HW-CROC-S", "name": "Crocodile Terminal Clips Small", "cat": "Electronics & Small Appliances", "cost": 30, "retail": 60, "stock": 80, "serial": False},
            {"barcode": "HW-CROC-M", "name": "Crocodile Terminal Clips Medium", "cat": "Electronics & Small Appliances", "cost": 50, "retail": 100, "stock": 60, "serial": False},
            {"barcode": "HW-CROC-B", "name": "Crocodile Terminal Clips Big", "cat": "Electronics & Small Appliances", "cost": 80, "retail": 150, "stock": 50, "serial": False},
            {"barcode": "TL-SOLD-REEL", "name": "Solder Lead Wire Reel", "cat": "Electronics & Small Appliances", "cost": 350, "retail": 600, "stock": 25, "serial": False},
            {"barcode": "TL-SOLD-PH200", "name": "Soldering Iron PH-200T", "cat": "Electronics & Small Appliances", "cost": 650, "retail": 1200, "stock": 12, "serial": False},
            {"barcode": "TL-SOLD-PH300", "name": "Soldering Iron PH-300T High-temp", "cat": "Electronics & Small Appliances", "cost": 850, "retail": 1500, "stock": 10, "serial": False},
            {"barcode": "TV-ICA-24", "name": "ICA 24-Inch LED Digital TV", "cat": "Electronics & Small Appliances", "cost": 8500, "retail": 12500, "stock": 3, "serial": True, "serials": "TVICA24-001,TVICA24-002,TVICA24-003"},
            {"barcode": "TV-WYN-24", "name": "Wynix 24-Inch LED Digital TV", "cat": "Electronics & Small Appliances", "cost": 9000, "retail": 13500, "stock": 2, "serial": True, "serials": "TVWYN24-901,TVWYN24-902"},
            {"barcode": "TV-WYN-22", "name": "Wynix 22-Inch LED Digital TV", "cat": "Electronics & Small Appliances", "cost": 8000, "retail": 11500, "stock": 2, "serial": True, "serials": "TVWYN22-801,TVWYN22-802"},
            {"barcode": "TV-ICA-22", "name": "ICA 22-Inch LED Digital TV", "cat": "Electronics & Small Appliances", "cost": 7500, "retail": 11000, "stock": 3, "serial": True, "serials": "TVICA22-771,TVICA22-772,TVICA22-773"},
            {"barcode": "TV-AMT-24", "name": "Amtel 24-Inch LED Digital TV", "cat": "Electronics & Small Appliances", "cost": 8500, "retail": 12500, "stock": 2, "serial": True, "serials": "TVAMT24-601,TVAMT24-602"},
            {"barcode": "TV-STAND", "name": "TV Wall Mount Stand Bracket", "cat": "Electronics & Small Appliances", "cost": 450, "retail": 800, "stock": 15, "serial": False},
            {"barcode": "RAD-XB-5155", "name": "NS5155 X-Bass FM Radio", "cat": "Electronics & Small Appliances", "cost": 850, "retail": 1400, "stock": 10, "serial": False},
            {"barcode": "RAD-L8", "name": "Radio L8 Compact FM/AM", "cat": "Electronics & Small Appliances", "cost": 600, "retail": 1000, "stock": 15, "serial": False},
            {"barcode": "RAD-YSM028", "name": "Radio YSM-028 Retro Style", "cat": "Electronics & Small Appliances", "cost": 1000, "retail": 1600, "stock": 8, "serial": False},
            {"barcode": "RAD-DG33", "name": "Radio DG33 Portable Speaker Receiver", "cat": "Electronics & Small Appliances", "cost": 900, "retail": 1500, "stock": 10, "serial": False},
            {"barcode": "RAD-CE333", "name": "Radio CE333 Classic Receiver", "cat": "Electronics & Small Appliances", "cost": 750, "retail": 1200, "stock": 12, "serial": False},
            {"barcode": "RAD-CAST-H102", "name": "Radio Caston ST-H102 Multi-band", "cat": "Electronics & Small Appliances", "cost": 1100, "retail": 1800, "stock": 8, "serial": False},
            {"barcode": "RAD-STC88", "name": "Radio ST-C88 Digital Receiver", "cat": "Electronics & Small Appliances", "cost": 950, "retail": 1500, "stock": 12, "serial": False},
            {"barcode": "RAD-FP518", "name": "Radio FP518 Multi-band Receiver", "cat": "Electronics & Small Appliances", "cost": 850, "retail": 1400, "stock": 12, "serial": False},
            {"barcode": "RAD-AI10951", "name": "Radio AI-10951 High Sensitivity", "cat": "Electronics & Small Appliances", "cost": 1000, "retail": 1650, "stock": 8, "serial": False}
        ]

        self.stdout.write(f'Loading {len(products_to_create)} custom products...')

        for p in products_to_create:
            Product.objects.create(
                barcode=p["barcode"],
                name=p["name"],
                description=f"Standard retail stock item: {p['name']}.",
                category=categories[p["cat"]],
                cost_price=decimal.Decimal(str(p["cost"])),
                retail_price=decimal.Decimal(str(p["retail"])),
                stock_quantity=p["stock"],
                serial_tracked=p["serial"],
                serial_numbers=p.get("serials", "")
            )

        # 6. Audit Log
        AuditLog.objects.create(
            action="SYSTEM_INIT",
            details="System database successfully seeded with custom Lights Electricals and Electronics stock lists."
        )

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded database with {len(products_to_create)} products!'))
